// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD NEW POSTS:
//   1. Add a new BlogPost object to BLOG_POSTS below.
//   2. Set publishedAt to a future YYYY-MM-DD date. The post will automatically
//      appear on the website on that date — no code changes needed.
//   3. Recommended cadence: one post every 3–4 days.
// ─────────────────────────────────────────────────────────────────────────────

export type ContentBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'ol'; items: string[] }
  | { type: 'quote'; text: string }
  | { type: 'tip'; heading: string; text: string }
  | { type: 'divider' };

export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  coverImage: string;
  publishedAt: string; // YYYY-MM-DD — auto-publishes on this date
  readTime: number;    // estimated minutes
  category: string;
  categoryColor: string; // Tailwind bg class
  tags: string[];
  content: ContentBlock[];
}

export const BLOG_POSTS: BlogPost[] = [
  // ── POST 1 ───────────────────────────────────────────────────────────────
  {
    id: 'post-1',
    slug: 'top-10-diwali-gift-ideas-gujarati-families',
    title: 'Top 10 Diwali Gift Ideas for Gujarati Families',
    excerpt: 'Diwali is the festival where relationships are renewed through thoughtful gifts. We\'ve curated 10 ideas that strike the perfect balance between tradition and meaning — for every budget.',
    coverImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-03',
    readTime: 5,
    category: 'Gifting',
    categoryColor: 'bg-coral/10 text-coral',
    tags: ['diwali', 'gifting', 'gujarati', 'festival'],
    content: [
      { type: 'p', text: 'Diwali is not just a festival of lights — it is a festival of relationships. In Gujarat especially, the act of gifting during Diwali carries deep meaning. It is a gesture of gratitude, a token of affection, and a way of saying "you matter to me." But with markets overflowing with options, choosing something truly meaningful can feel overwhelming. We have put together this list to help you find something that will be remembered long after the diyas have been extinguished.' },
      { type: 'h2', text: 'Why Traditional Food Gifts Win Every Time' },
      { type: 'p', text: 'Diwali is, at its core, a festival of flavors. From chakli to the delicate crunch of fennel seeds — food is deeply woven into this celebration. When you gift someone a handcrafted food hamper, you are not just giving a product; you are giving an experience that gets shared at the dining table with family. That is why food gifts consistently rank as the most appreciated Diwali presents.' },
      { type: 'h2', text: '1. A Handcrafted Mukhwas Hamper' },
      { type: 'p', text: 'The quintessential Gujarati gift. A beautifully curated mukhwas hamper — especially one made fresh at home with no artificial preservatives — signals both tradition and care. Think five different varieties of mukhwas in airtight glass jars, presented in a handmade wooden box. This is the gift that gets displayed before it gets opened.' },
      { type: 'h2', text: '2. A Personalized Snack Box' },
      { type: 'p', text: 'When you can personalize what goes inside — choosing specific mukhwas varieties, masalas or snacks that you know the recipient will love — the gift transforms from generic to genuinely thoughtful. At Amie\'s, you can choose exactly which traditional treats go into the Heritage Box, making every hamper one-of-a-kind.' },
      { type: 'h2', text: '3. Sugar-Free Options for Health-Conscious Elders' },
      { type: 'p', text: 'With diabetes affecting nearly 77 million Indians, many families have at least one elder who must watch their sugar intake. A sugar-free mukhwas hamper — made with plain fennel seeds, coriander, and sesame — is the gift that says "I thought about your health, not just your taste buds." This is one of the most loving things you can gift to a diabetic grandparent or parent.' },
      { type: 'h2', text: '4. The Wellness Gift Box' },
      { type: 'p', text: 'For the health-first family, a wellness-focused hamper featuring natural seeds, no added sugar, and functional ingredients — ajwain for digestion, fennel for cooling, sesame for nutrients — is a truly thoughtful choice. It says "I care about you" in a language that goes beyond the festival.' },
      { type: 'h2', text: '5. The Corporate Gifting Hamper' },
      { type: 'p', text: 'If you are gifting clients, vendors or business partners this Diwali, a premium Indian food hamper stands out from the sea of standard corporate gifts. It is personal, culturally relevant, and memorable. A wooden presentation box of artisanal mukhwas will be talked about in the office.' },
      { type: 'h2', text: 'The Complete Top 10 List' },
      { type: 'ol', items: [
        'Handcrafted Mukhwas Hamper — traditional and deeply Gujarati',
        'Personalized Heritage Snack Box — choose what goes inside',
        'Sugar-Free Gift Set — for diabetic elders and health-conscious recipients',
        'Wellness Box — functional seeds and no added sugar',
        'Corporate Gifting Hamper — for clients and business relationships',
        'Premium Dry Fruit & Mukhwas Combo — the classic pairing',
        'Artisan Tea + Mukhwas Set — perfect for the chai lover in your life',
        'Children\'s Snack Box — fun-sized treats kids will love',
        'Eco-Friendly Hamper in a Reusable Wooden Box — sustainable gifting',
        'The Grand Heritage Hamper — for your most important relationships',
      ]},
      { type: 'tip', heading: 'Pro Tip: Order Early', text: 'Diwali hampers at Amie\'s are made fresh in small batches and sell out every year. Place your order at least 7–10 days in advance to guarantee delivery before the festival.' },
      { type: 'p', text: 'This Diwali, gift something that will be remembered. Whether you choose a classic mukhwas set or a personalized hamper, the thought behind the gift is what truly makes it shine.' },
    ],
  },

  // ── POST 2 ───────────────────────────────────────────────────────────────
  {
    id: 'post-2',
    slug: 'why-homemade-mukhwas-beats-store-bought',
    title: 'Why Homemade Mukhwas Beats Store-Bought Every Time',
    excerpt: 'Walk into a supermarket and you\'ll find shelves of colorful mukhwas. But turn any packet over and look at the ingredients. Here\'s why homemade always wins — and how to tell the difference.',
    coverImage: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-06',
    readTime: 4,
    category: 'Food & Lifestyle',
    categoryColor: 'bg-amber-100 text-amber-700',
    tags: ['mukhwas', 'homemade', 'quality', 'natural'],
    content: [
      { type: 'p', text: 'If you have ever bought mukhwas from a supermarket and compared it to something made at home — you know the difference. It is not just taste; it is color, aroma, texture, and the peace of mind that comes from knowing exactly what went into it. Here is why homemade mukhwas will always win.' },
      { type: 'h2', text: 'The Problem with Commercial Mukhwas' },
      { type: 'p', text: 'Walk into any supermarket and you\'ll find shelves lined with colorful mukhwas packets. But turn any of them over and look at the ingredients list. Artificial food colors, refined sugar coatings, synthetic flavor enhancers, and preservatives with names you can\'t pronounce. Many of those neon-green fennel seeds have been dyed with artificial colors. Those candy-coated seeds contain refined sugar that offers no nutritional value and masks the natural flavor of the seed entirely.' },
      { type: 'h2', text: 'What Changes When It Is Made at Home' },
      { type: 'p', text: 'Homemade mukhwas uses only real ingredients. The fennel seeds are raw or lightly roasted. The coriander seeds are natural. The coconut is dried — not processed. The flavors come from genuine spices like dried rose petals, ajwain, and elaichi — not from synthetic "natural flavor" additives. When Ami Shah makes a batch of mukhwas at Amie\'s Homemade, the ingredient list is short and completely legible.' },
      { type: 'h2', text: 'The Freshness Factor' },
      { type: 'p', text: 'Commercial mukhwas sits in warehouses, then distribution centers, then on supermarket shelves for weeks or months. Homemade mukhwas, made in small batches, is typically consumed within weeks of being made. This is not just a taste difference — it is a nutritional one. Fresher fennel seeds retain more of their volatile oils, which are responsible for their genuine digestive and breath-freshening properties.' },
      { type: 'h2', text: 'How to Tell Real Mukhwas from the Processed' },
      { type: 'ul', items: [
        'Color: Natural mukhwas has muted, earthy tones. Unnaturally bright colors suggest artificial dye.',
        'Smell: Genuine mukhwas smells herbaceous and spiced. Synthetic mukhwas often has a candy-like artificial scent.',
        'Texture: Homemade mukhwas is softer and more natural. Heavily processed mukhwas is often crunchy from sugar coating.',
        'Ingredients: If the list is long and includes chemical names, it is probably not real.',
      ]},
      { type: 'tip', heading: 'The Simple Test', text: 'Pour a bit of mukhwas into water. Natural mukhwas will release oils and light sediment. Artificially colored mukhwas will immediately start to bleed dye into the water.' },
      { type: 'p', text: 'The next time you reach for a packet of commercial mukhwas, pause and ask: does this have real ingredients? Is it made fresh? If you are not sure, it is worth choosing something homemade — your body and your taste buds will both thank you.' },
    ],
  },

  // ── POST 3 ───────────────────────────────────────────────────────────────
  {
    id: 'post-3',
    slug: 'best-mukhwas-for-diabetics',
    title: 'Best Mukhwas for Diabetics: Enjoying Tradition Without the Sugar',
    excerpt: 'Managing diabetes during Indian festivals can feel restrictive. But traditional mukhwas ingredients — saunf, dhana, til, ajwain — are naturally low-GI and often beneficial for blood sugar. Here\'s what to look for.',
    coverImage: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-10',
    readTime: 4,
    category: 'Health & Wellness',
    categoryColor: 'bg-green-100 text-green-700',
    tags: ['diabetic', 'sugar-free', 'health', 'mukhwas'],
    content: [
      { type: 'p', text: 'Managing diabetes during Indian festivals can feel like navigating a minefield. The sweets are out. The mithai is off-limits. Even many commercial mukhwas varieties are loaded with refined sugar coatings. But here is the good news: traditional Indian mouth fresheners, in their natural form, are actually among the most diabetic-friendly treats you can enjoy.' },
      { type: 'h2', text: 'Many Traditional Mukhwas Ingredients Are Naturally Low-GI' },
      { type: 'p', text: 'The real ingredients in traditional mukhwas — fennel seeds, coriander seeds, sesame seeds, ajwain, and cardamom — have naturally low glycemic indices. They do not cause the blood sugar spike that refined sugars do. In fact, many of these ingredients have been studied for their ability to support better blood sugar management. This is ancient Ayurvedic wisdom being confirmed by modern research.' },
      { type: 'h2', text: 'The Best Mukhwas Ingredients for Diabetics' },
      { type: 'ul', items: [
        'Saunf (Fennel Seeds): Rich in magnesium, which plays a role in insulin regulation. Studies suggest fennel may help lower blood glucose levels.',
        'Dhana (Coriander Seeds): Traditionally used in Ayurveda to stimulate insulin secretion and support healthy blood sugar. Naturally low in sugar.',
        'Til (Sesame Seeds): Contain pinoresinol, a compound that may help regulate blood sugar by inhibiting the enzyme maltase.',
        'Ajwain (Carom Seeds): Known to support digestive health and reduce blood sugar spikes after meals.',
        'Elaichi (Cardamom): A powerful antioxidant that has shown promise in reducing blood glucose levels in clinical studies.',
      ]},
      { type: 'h2', text: 'What Diabetics Should Avoid in Commercial Mukhwas' },
      { type: 'ul', items: [
        'Sugar-coated fennel seeds — especially the brightly colored variety',
        'Candy-style mukhwas with hard sugar shells',
        'Any mukhwas listing glucose syrup, maltose, or dextrose in the ingredients',
        'Varieties with artificial sweeteners if your doctor has advised against those',
      ]},
      { type: 'h2', text: 'Gifting Tips for Diabetic Family Members' },
      { type: 'p', text: 'When gifting mukhwas to a diabetic elder, look for plain, uncoated varieties with no added sugar. Amie\'s Homemade offers mukhwas made purely from natural seeds with no sugar coating — ideal for diabetics who still want to enjoy the traditional post-meal ritual without the guilt.' },
      { type: 'tip', heading: 'Ask Before You Gift', text: 'If you are unsure whether a family member\'s doctor has specific restrictions, err on the side of caution and gift a plain saunf-only or dhana-til mix. These are among the safest and most universally enjoyed varieties for diabetics.' },
      { type: 'p', text: 'Diabetes does not have to mean sitting out the Diwali mukhwas tradition. With the right choices, your diabetic family members can enjoy the flavors of the season without compromising their health.' },
    ],
  },

  // ── POST 4 ───────────────────────────────────────────────────────────────
  {
    id: 'post-4',
    slug: 'gujarati-snacks-for-corporate-gifting',
    title: 'Gujarati Snacks for Corporate Gifting: Why Authenticity Wins',
    excerpt: 'Every Diwali, offices across India struggle with the same question: what do we give clients that doesn\'t feel generic? The answer is sitting right in Gujarati culinary tradition.',
    coverImage: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-14',
    readTime: 4,
    category: 'Corporate Gifting',
    categoryColor: 'bg-blue-100 text-blue-700',
    tags: ['corporate', 'gifting', 'gujarati', 'snacks'],
    content: [
      { type: 'p', text: 'Every October-November, offices across India grapple with the same question: what do we give our clients this Diwali that does not feel generic, forgettable, or wasteful? The answer, more often than people realize, is sitting right in Gujarati culinary tradition.' },
      { type: 'h2', text: 'Why Generic Corporate Gifts Fall Short' },
      { type: 'p', text: 'Branded mugs. Desk organizers. Diary sets. These gifts check the "we gave something" box, but they rarely create a meaningful impression. Food gifts are consistently ranked among the most appreciated corporate gifts — precisely because they create an experience, not just an object. They get shared at home. They get talked about. And they leave a residual warmth that a branded pen simply cannot.' },
      { type: 'h2', text: 'The Case for Authentic Gujarati Snacks' },
      { type: 'p', text: 'Gujarati food culture is widely respected across India. When you gift someone a hamper of handmade mukhwas, chakli, or premium snacks made in small batches by a home kitchen — you are giving them a piece of a culinary tradition with centuries of history behind it. It signals discernment. It shows you value authenticity over convenience. That message lands with clients.' },
      { type: 'h2', text: 'Gift Hamper Options by Budget' },
      { type: 'ul', items: [
        'Under ₹600: A curated selection of 2–3 mukhwas varieties in premium glass jars — compact, elegant, and impactful.',
        '₹600–₹1,500: The Wellness Box or similar mid-range hamper with 4–5 products in a handcrafted presentation.',
        '₹1,500 and above: The Heritage Box — a full luxury hamper in a wooden presentation case with custom contents. Ideal for senior clients or VIP relationships.',
      ]},
      { type: 'h2', text: 'The Bulk Order Advantage' },
      { type: 'p', text: 'When you order 20+ corporate gift hampers from Amie\'s, you get custom pricing, a consistent look and feel, and the assurance that every hamper is made fresh — not pulled from warehouse stock. Each hamper is made to order, which means no two-year-old nuts hidden inside a shiny box.' },
      { type: 'tip', heading: 'Add a Personal Touch', text: 'Ask for a custom card to be included with each hamper. Even a simple "Wishing you a warm Diwali from [Company Name]" makes the gift feel curated rather than mass-ordered. This small gesture dramatically increases how the recipient perceives the gift.' },
      { type: 'p', text: 'In a world of forgettable gifts, a handcrafted food hamper stands out. And in a culture where food is hospitality, gifting authentic homemade snacks is one of the most thoughtful things a business can do for the people who matter most.' },
    ],
  },

  // ── POST 5 ───────────────────────────────────────────────────────────────
  {
    id: 'post-5',
    slug: 'what-is-mukhwas-complete-guide',
    title: 'What is Mukhwas? A Complete Guide to India\'s Favourite After-Meal Tradition',
    excerpt: 'If you\'ve ever reached into a silver bowl at the end of a Gujarati meal and taken a pinch of fennel and coriander — you\'ve had mukhwas. But what is it, where does it come from, and why has it lasted thousands of years?',
    coverImage: 'https://images.unsplash.com/photo-1585399000684-d2f72660f092?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-18',
    readTime: 5,
    category: 'Culture & Tradition',
    categoryColor: 'bg-purple-100 text-purple-700',
    tags: ['mukhwas', 'tradition', 'ayurveda', 'guide'],
    content: [
      { type: 'p', text: 'If you have ever been to a Gujarati home and noticed a small ornate bowl of colorful seeds near the dining table — you have seen mukhwas. If you have ever reached into a silver dish at the end of a thali meal and taken a pinch of fennel and coriander seeds — you have had mukhwas. But what exactly is it, where does it come from, and why has it been a staple of Indian households for centuries?' },
      { type: 'h2', text: 'The Meaning of the Word' },
      { type: 'p', text: 'The word "mukhwas" comes from Sanskrit: mukh (मुख) meaning mouth, and vas (वास) meaning fragrance or dwelling. Literally, it means "that which dwells in the mouth" — or more poetically, "the fragrance of the mouth." It is the perfect name for something designed to freshen breath, aid digestion, and leave a pleasant lingering flavor after a meal.' },
      { type: 'h2', text: 'Ancient Roots' },
      { type: 'p', text: 'Mukhwas is not a modern invention. References to mouth fresheners using fennel, cardamom, and betel leaves appear in ancient Ayurvedic texts like the Charaka Samhita, written thousands of years ago. Ayurveda considered certain seeds — particularly fennel and cardamom — as essential aids to digestion and balancing of the body\'s doshas, especially pitta. What started as medicine became tradition, and tradition became culture.' },
      { type: 'h2', text: 'The Main Ingredients and Their Traditional Roles' },
      { type: 'ul', items: [
        'Saunf (Fennel): The anchor of most mukhwas. Cooling, digestive, and known to freshen breath naturally.',
        'Dhana (Coriander Seeds): Liver-supporting and cooling. Often paired with saunf for a milder, gentler flavor.',
        'Elaichi (Cardamom): The aromatic luxury of mukhwas. Powerfully digestive and known to neutralize bad breath at the source.',
        'Til (Sesame Seeds): Nutritious and slightly nutty. Added for texture and meaningful calcium content.',
        'Ajwain (Carom Seeds): The functional star — excellent for gas relief and post-meal indigestion.',
        'Dried Rose Petals: A signature Gujarati touch that adds floral fragrance and visual beauty.',
        'Amchur (Dried Mango Powder): Sometimes added for a tangy note that balances richer spices.',
      ]},
      { type: 'h2', text: 'The Gujarati Tradition' },
      { type: 'p', text: 'In Gujarat, offering mukhwas at the end of a meal is considered mandatory hospitality. Restaurants serve it automatically at checkout. Homes keep a dedicated silver or copper bowl of mukhwas on the dining table year-round. At weddings, specially curated mukhwas is given as a wedding favor. It is a gesture of completion — a graceful way to close the meal and send guests on their way with sweetness.' },
      { type: 'h2', text: 'Traditional vs. Modern Mukhwas' },
      { type: 'p', text: 'Traditional mukhwas is uncoated, made from natural seeds, and relies entirely on the inherent flavors of its ingredients. Modern commercial mukhwas often involves sugar coating, artificial colors, and synthetic flavor enhancers that mask the actual seed. The best mukhwas — like what is made at Amie\'s Homemade — remains close to its roots: simple, natural, and deeply flavorful.' },
      { type: 'tip', heading: 'How to Serve Mukhwas', text: 'Store mukhwas in an airtight glass jar at room temperature, away from direct sunlight. Serve in a small bowl at the end of meals. A teaspoon is typically enough — mukhwas is meant to be savored slowly, not consumed in handfuls.' },
      { type: 'p', text: 'Mukhwas is more than a mouth freshener. It is an ancient ritual, a cultural marker, and a daily practice of mindful eating. Every time you take a pinch after a meal, you are participating in a tradition that stretches back thousands of years — and has been perfected ever since.' },
    ],
  },

  // ── POST 6 ───────────────────────────────────────────────────────────────
  {
    id: 'post-6',
    slug: 'how-to-build-perfect-indian-gift-hamper',
    title: 'How to Build the Perfect Indian Gift Hamper: A Step-by-Step Guide',
    excerpt: 'A gift hamper is only as good as the thought that went into building it. Anyone can fill a basket with random items. Here\'s how to build one that will actually be remembered.',
    coverImage: 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-22',
    readTime: 5,
    category: 'Gifting',
    categoryColor: 'bg-coral/10 text-coral',
    tags: ['hamper', 'gifting', 'guide', 'tips'],
    content: [
      { type: 'p', text: 'A gift hamper is only as good as the thought that went into building it. Anyone can fill a basket with random items and wrap it in cellophane. But a truly memorable hamper tells a story — about the recipient, the occasion, and the care the giver put in. Here is how to build one that will be remembered long after it is opened.' },
      { type: 'h2', text: 'Step 1 — Define the Occasion' },
      { type: 'p', text: 'The occasion sets the tone for everything else. A Diwali hamper should feel festive and abundant. A birthday hamper should feel personal and celebratory. A corporate hamper should feel polished and professional. A get-well-soon hamper should feel gentle and nurturing. Know your occasion before you pick a single item — it will make every other decision easier.' },
      { type: 'h2', text: 'Step 2 — Know Your Recipient' },
      { type: 'p', text: 'This is where most people get hampers wrong. They build hampers they would want to receive, not what the recipient would love. Ask yourself:' },
      { type: 'ul', items: [
        'Do they have any dietary restrictions? (diabetic, vegan, gluten-free)',
        'What flavors do they prefer? (spicy, tangy, sweet, mild)',
        'What is their lifestyle? (health-first? traditional? adventurous?)',
        'What is the relationship? (close family, acquaintance, business partner)',
      ]},
      { type: 'h2', text: 'Step 3 — Choose a Theme' },
      { type: 'p', text: 'The best hampers have a coherent theme, not a random assortment. Consider:' },
      { type: 'ul', items: [
        'The Traditional Gujarati Hamper: Mukhwas, chakli, masala, and perhaps a small jar of gur.',
        'The Wellness Hamper: Sugar-free mukhwas, herbal seeds, and functional snacks.',
        'The Festive Hamper: Everything seasonal and celebratory — for Diwali, Navratri, or weddings.',
        'The Corporate Hamper: Premium, minimal, and polished — appropriate for professional relationships.',
      ]},
      { type: 'h2', text: 'Step 4 — Select Contents That Complement Each Other' },
      { type: 'p', text: 'The items in a hamper should have a natural flow. If you start with a spicy snack, balance it with something cooling. If you include a rich treat, pair it with a digestive mukhwas. Variety is good — redundancy is not. Three different mukhwas varieties is variety. Ten items that all taste the same is not a hamper, it is a bag of the same thing.' },
      { type: 'h2', text: 'Step 5 — Presentation is Part of the Gift' },
      { type: 'p', text: 'The box, the wrapping, the ribbon — these are not extras. They are the first thing the recipient sees. A beautiful wooden box filled with artisanal products communicates premium quality before a single item is tasted. If you are doing a corporate order, consider custom branding on the box lid or a handwritten tag for each recipient.' },
      { type: 'h2', text: 'Common Mistakes to Avoid' },
      { type: 'ul', items: [
        'Including items you like but the recipient does not enjoy',
        'Mixing products of wildly different quality levels',
        'Skimping on presentation because "it is what is inside that counts"',
        'Ordering at the last minute and missing the delivery window',
        'Forgetting to check for dietary restrictions',
      ]},
      { type: 'tip', heading: 'The Handwritten Note Makes the Difference', text: 'In a world of WhatsApp messages and email, a handwritten card inside a gift hamper stands out dramatically. Even three lines — "I was thinking of you and wanted to share something made with love" — transforms the hamper from a product into a memory.' },
      { type: 'p', text: 'The best gift hamper is one that makes the recipient feel truly seen. It does not need to be the most expensive one. It needs to show that you listened, you observed, and you cared enough to put something together just for them.' },
    ],
  },

  // ── POST 7 ───────────────────────────────────────────────────────────────
  {
    id: 'post-7',
    slug: 'health-benefits-of-saunf-fennel-seeds',
    title: 'Health Benefits of Saunf (Fennel Seeds): India\'s Ancient Digestive Superfood',
    excerpt: 'You\'ve been eating saunf after meals your whole life. But do you know what it\'s actually doing for your body? The science behind this tiny seed is remarkable.',
    coverImage: 'https://images.unsplash.com/photo-1532634922-8fe0b757fb13?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-26',
    readTime: 5,
    category: 'Health & Wellness',
    categoryColor: 'bg-green-100 text-green-700',
    tags: ['fennel', 'saunf', 'health', 'ayurveda'],
    content: [
      { type: 'p', text: 'Chances are you have eaten saunf without giving it much thought — a quick handful after a meal at a restaurant, or a few seeds from the bowl at your grandmother\'s dining table. But fennel seeds are far more than a simple mouth freshener. They are one of the most nutritionally dense seeds in the Indian pantry, and Ayurveda has known this for millennia.' },
      { type: 'h2', text: 'What\'s Actually in a Fennel Seed?' },
      { type: 'p', text: 'Despite being tiny, fennel seeds pack a meaningful nutritional punch. One tablespoon (about 6 grams) contains 20 calories, 1 gram of fiber, meaningful amounts of calcium, iron, and magnesium, vitamin C, potassium, and manganese. But the real magic is in the volatile aromatic oils — anethole, fenchone, and estragole — which are responsible for both the distinctive flavor and most of the health benefits.' },
      { type: 'h2', text: 'The Top 7 Health Benefits of Saunf' },
      { type: 'h3', text: '1. Aids Digestion' },
      { type: 'p', text: 'Fennel has powerful antispasmodic properties. Its volatile oils relax the smooth muscles of the digestive tract, reducing bloating, gas, and cramping. This is precisely why it is served after meals — it is not just tradition, it is functional medicine that Ayurveda understood long before modern gastroenterology confirmed it.' },
      { type: 'h3', text: '2. Freshens Breath Naturally' },
      { type: 'p', text: 'The antimicrobial properties of fennel seeds inhibit bacterial growth in the mouth — bacteria being the primary cause of bad breath. Chewing a few seeds releases essential oils that neutralize odor at the source, unlike mint candies which simply mask it temporarily.' },
      { type: 'h3', text: '3. Supports Heart Health' },
      { type: 'p', text: 'Fennel is rich in nitrites, compounds known to help dilate blood vessels and support healthy blood pressure. Its high potassium content further supports cardiovascular function. Regular moderate consumption as part of a balanced diet may contribute to long-term heart health.' },
      { type: 'h3', text: '4. Rich in Antioxidants' },
      { type: 'p', text: 'Fennel seeds contain quercetin, kaempferol, and several flavonoids — antioxidants that help neutralize free radicals and reduce oxidative stress. This is one reason traditional mukhwas was considered a daily health practice, not merely a flavor preference.' },
      { type: 'h3', text: '5. May Help Regulate Blood Sugar' },
      { type: 'p', text: 'The fiber and anethole in fennel seeds may help slow the absorption of glucose in the bloodstream, contributing to more stable blood sugar levels. This makes plain saunf one of the more diabetic-friendly post-meal treats available.' },
      { type: 'h3', text: '6. Supports Eye Health' },
      { type: 'p', text: 'The vitamin C content, combined with flavonoids, supports collagen synthesis in the cornea and may protect against oxidative damage to the eyes. Ancient Ayurvedic texts recommended fennel water for improving eyesight — a practice that continues in many traditional households today.' },
      { type: 'h3', text: '7. Anti-Inflammatory Properties' },
      { type: 'p', text: 'Anethole, the primary active compound in fennel, has been shown in multiple studies to have significant anti-inflammatory effects. This may be beneficial in reducing the risk of chronic inflammatory conditions when fennel is consumed regularly as part of a balanced diet.' },
      { type: 'h2', text: 'How Much Saunf Is Enough?' },
      { type: 'p', text: 'Half a teaspoon to one teaspoon of fennel seeds after meals is a well-tolerated daily amount for most adults. The traditional practice of a small handful after meals has always been intuitively calibrated for this range. As with anything, moderation is key.' },
      { type: 'tip', heading: 'Make Saunf Water', text: 'Soak one teaspoon of fennel seeds in a glass of water overnight. Strain and drink it first thing in the morning. It is a traditional Ayurvedic practice for gentle digestive support, hydration, and a mild anti-inflammatory boost to start the day.' },
      { type: 'p', text: 'The next time you take a pinch of mukhwas after dinner, know that you are not just freshening your breath — you are feeding your body one of nature\'s most versatile functional foods. That little seed has more going on inside it than most trendy superfoods combined.' },
    ],
  },

  // ── POST 9 ───────────────────────────────────────────────────────────────
  {
    id: 'post-9',
    slug: 'homemade-chakli-why-it-tastes-different',
    title: 'Homemade Chakli: Why It Tastes Completely Different from the Packet',
    excerpt: 'The chakli you grew up eating at your grandmother\'s house had a flavor that no branded version has ever matched. There\'s a reason for that — and it starts long before the dough is shaped.',
    coverImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-04-03',
    readTime: 5,
    category: 'Homemade Snacks',
    categoryColor: 'bg-orange-100 text-orange-700',
    tags: ['chakli', 'snacks', 'homemade', 'gujarati'],
    content: [
      { type: 'p', text: 'There is a particular flavor that chakli has when it is made at home — a deep, savory richness with a crunch that feels satisfying rather than hard. It is not something you can easily describe, but you know it the moment you taste it. And you know just as immediately when something is missing in the store-bought version. This is not nostalgia. It is chemistry, technique, and the simple fact that industrial production cannot replicate what a careful pair of hands can do.' },
      { type: 'h2', text: 'What is Chakli?' },
      { type: 'p', text: 'Chakli (also called murukku in South India) is one of India\'s most iconic savory snacks — a spiral-shaped, crispy fried or baked snack made primarily from rice flour and lentil flour, spiced with sesame seeds, ajwain, cumin, and sometimes chilli. It is a staple at Diwali, during Navratri snacking, and as a tea-time companion across Gujarat, Maharashtra, and Karnataka. The name comes from the Kannada word "chakra" — meaning wheel — for its characteristic coiled shape.' },
      { type: 'h2', text: 'The Problem with Commercial Chakli' },
      { type: 'p', text: 'Walk down any supermarket snack aisle and you will find chakli from a dozen brands. Most of them suffer from the same issues. The flour blends are standardized and often include additives to extend shelf life. The frying is done in bulk at industrial temperatures that prioritize volume over texture. The seasoning is calibrated for the broadest possible palate rather than authentic regional flavor. The result is a snack that is crispy, fine — but not quite right.' },
      { type: 'h2', text: 'Why Homemade Chakli is Different' },
      { type: 'ul', items: [
        'Flour Quality: Homemade chakli typically uses freshly milled or high-quality rice flour, not the standardized blends used in industrial production. The flour quality determines everything about the final texture.',
        'The Spice Ratio: Every home cook has their own precise balance of sesame, ajwain, cumin, and chilli. This personal calibration cannot be replicated at factory scale.',
        'The Dough Consistency: The chakli dough must be worked to exactly the right consistency — firm enough to hold its shape through the press, soft enough to not crack. This requires hands that know what they are feeling for.',
        'Freshness: Commercial chakli can sit in warehouses and on shelves for months. Homemade chakli is made fresh and consumed within weeks. The difference in flavor is significant.',
        'Oil Temperature: Deep-frying chakli requires carefully maintained oil temperature. In home production, this is closely monitored. In industrial settings, temperatures fluctuate more widely.',
      ]},
      { type: 'h2', text: 'The Signature Flavors of Gujarati Chakli' },
      { type: 'p', text: 'Gujarati chakli has a distinct character — it tends to be slightly milder on the chilli heat compared to South Indian murukku, with a stronger emphasis on sesame and ajwain. The texture is typically slightly softer and more crumbly than the harder South Indian variety. This makes it ideal as a tea-time snack and as a component in festive gift hampers.' },
      { type: 'h2', text: 'Chakli as a Gift — The Underrated Choice' },
      { type: 'p', text: 'Chakli is among the most thoughtful things you can include in an Indian gift hamper. Unlike sweets, it appeals to those who prefer savory. It pairs perfectly with tea or chai. It keeps well (1–3 weeks in an airtight container) and travels well, making it practical for shipping. At Amie\'s, freshly made chakli is available as part of the snack hamper selection — made in small batches with no added preservatives.' },
      { type: 'tip', heading: 'Storage Tip', text: 'Store chakli in an airtight container at room temperature. Keep it away from moisture — even a small amount of humidity can make it lose its signature crunch within a day. Never refrigerate chakli, as the cold moisture will soften it.' },
      { type: 'p', text: 'The best chakli is the kind that makes you reach for a second piece before you\'ve finished the first. That quality — the kind that makes snacking involuntary — is not an accident. It is the product of fresh ingredients, honest recipes, and someone who makes chakli the way it was always meant to be made.' },
    ],
  },

  // ── POST 10 ───────────────────────────────────────────────────────────────
  {
    id: 'post-10',
    slug: 'traditional-indian-ladoo-varieties-guide',
    title: 'A Guide to Traditional Indian Ladoo: Every Variety You Should Know',
    excerpt: 'Ladoo is perhaps India\'s most beloved mithai — offered at temples, shared at weddings, gifted at festivals. But not all ladoos are created equal. Here\'s a guide to the real varieties and what makes each one special.',
    coverImage: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-04-07',
    readTime: 5,
    category: 'Homemade Sweets',
    categoryColor: 'bg-yellow-100 text-yellow-800',
    tags: ['ladoo', 'sweets', 'mithai', 'homemade', 'traditional'],
    content: [
      { type: 'p', text: 'If there is one mithai that holds a place in every Indian household, every temple offering, every wedding feast, and every festive celebration — it is ladoo. This humble round sweet has been at the center of Indian food culture for over a thousand years. Yet its diversity is staggering. Besan ladoo is nothing like motichur ladoo. Til ladoo shares almost nothing in common with nariyal ladoo except the shape. Each variety carries its own history, its own technique, and its own set of loyal devotees.' },
      { type: 'h2', text: 'Why Ladoo Endures' },
      { type: 'p', text: 'Ladoo has survived millennia of changing food fashions for several reasons. It is nutritionally dense — made from ingredients like chickpea flour, jaggery, sesame, and ghee that provide sustained energy. It keeps well without refrigeration, which made it practical in the age before preservatives. It is hand-formed, which gives it a handmade quality that feels personal. And it is endlessly customizable — the same basic idea of a sweet sphere can become hundreds of distinct flavor profiles.' },
      { type: 'h2', text: 'The Most Beloved Ladoo Varieties' },
      { type: 'h3', text: 'Besan Ladoo' },
      { type: 'p', text: 'Made from roasted chickpea flour (besan), ghee, and sugar or powdered jaggery, besan ladoo is the most common variety in Gujarat and Rajasthan. The key to a good besan ladoo is patience — the besan must be roasted slowly in ghee until it turns golden and fragrant. Rushing this step produces a raw, bitter flavor that no amount of sugar can fix. When done right, besan ladoo has a deep, nutty warmth that is deeply satisfying.' },
      { type: 'h3', text: 'Motichur Ladoo' },
      { type: 'p', text: 'These are the ladoos of special occasions — delicate, finely textured spheres made from tiny droplets of fried besan batter that are soaked in sugar syrup and then pressed together. The name "motichur" means crushed pearl, which describes the fine, pearl-like texture of the interior. Motichur ladoo requires considerable skill and is typically made by specialist mithai shops or very experienced home cooks.' },
      { type: 'h3', text: 'Til (Sesame) Ladoo' },
      { type: 'p', text: 'A winter staple and a Makar Sankranti essential, til ladoo is made from roasted sesame seeds bound together with jaggery. It is one of the most nutrient-dense ladoo varieties — sesame is rich in calcium, healthy fats, and protein, and jaggery provides iron and minerals. The flavor is distinctly nutty and molasses-rich. Til ladoo is the original "superfood" sweet — made from functional ingredients long before the term existed.' },
      { type: 'h3', text: 'Nariyal (Coconut) Ladoo' },
      { type: 'p', text: 'Made from dried or fresh coconut with condensed milk or sugar and often flavored with cardamom, nariyal ladoo is moist, sweet, and aromatic. It is particularly popular in the coastal regions of India and during Navratri when certain fasting practices allow coconut-based sweets. The freshness of the coconut determines the quality of the ladoo — freshly grated or high-quality desiccated coconut produces a dramatically different result than the generic variety.' },
      { type: 'h3', text: 'Rava (Semolina) Ladoo' },
      { type: 'p', text: 'Rava ladoo has a slightly gritty, fudge-like texture that sets it apart from the flour-based varieties. Made from roasted semolina, ghee, sugar, and cashews, it is quick to prepare and has a warm, grainy sweetness that is less cloying than besan or motichur. It is a Maharashtrian and South Indian favorite, increasingly popular across Gujarat.' },
      { type: 'h2', text: 'How to Tell a Good Ladoo from a Poor One' },
      { type: 'ul', items: [
        'Texture: A properly made ladoo should hold its shape without being compressed or crumbly. It should give slightly when pressed, not crack or powder.',
        'Flavor: The ingredient flavors should be forward — you should taste the besan, the sesame, or the coconut clearly. If all you taste is sweetness, the base has been compromised.',
        'Ghee: Real ladoo is made with ghee. Its absence is immediately detectable — the richness, the aroma, and the finish are completely different when ghee is replaced with refined oil.',
        'No Artificial Flavors: Traditional ladoo needs no artificial vanilla or flavor essences. The ingredients themselves are the flavor.',
      ]},
      { type: 'tip', heading: 'Gifting Ladoo', text: 'For gifting, til ladoo and besan ladoo are the most practical — they have a shelf life of 10–15 days at room temperature (longer than coconut-based varieties). Nariyal ladoo should be refrigerated and consumed within 5 days of making. Pack ladoos in a single layer to prevent them from pressing together and losing their shape during transport.' },
      { type: 'p', text: 'Every ladoo tells a story about where it was made, who made it, and what recipe has been passed down through generations. The best ladoo is always the one made by someone who has made it a hundred times before — because the repetition is where mastery lives.' },
    ],
  },

  // ── POST 11 ───────────────────────────────────────────────────────────────
  {
    id: 'post-11',
    slug: 'navratri-gift-ideas-festive-hampers',
    title: 'Navratri Gift Ideas: Thoughtful Homemade Hampers for the Festival Season',
    excerpt: 'Navratri is nine nights of devotion, dance, and togetherness. It\'s also one of the most meaningful times to gift something handmade. Here\'s how to choose (or build) the perfect Navratri hamper.',
    coverImage: 'https://images.unsplash.com/photo-1604999333679-b86d54738315?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-04-11',
    readTime: 5,
    category: 'Festive Gifting',
    categoryColor: 'bg-pink-100 text-pink-700',
    tags: ['navratri', 'gifting', 'festival', 'hamper', 'homemade'],
    content: [
      { type: 'p', text: 'Navratri — nine nights of Garba, devotion, color, and community — is one of Gujarat\'s most deeply felt festivals. In Ahmedabad especially, the energy during Navratri is unlike anything else. It is a time when families gather, communities celebrate, and the act of sharing good food and thoughtful gifts carries extra meaning. Yet Navratri gifting is often an afterthought. People default to boxes of commercial mithai or generic hampers. Here is how to do better.' },
      { type: 'h2', text: 'What Makes Navratri Gifting Unique' },
      { type: 'p', text: 'Unlike Diwali — where the emphasis is on grand gestures and festive abundance — Navratri gifts tend to be more personal and intimate. They are given to close family, neighbors, the women in your garba group, your daughter\'s dance teacher. The occasion calls for something heartfelt over something impressive. Homemade treats have a natural advantage here: they communicate effort, care, and personal connection in a way that no commercial product can.' },
      { type: 'h2', text: 'Fasting-Friendly Gift Ideas' },
      { type: 'p', text: 'A significant portion of Navratri observers fast during some or all of the nine nights — eating only certain foods (sattvic diet, no grains) or abstaining from meals until the evening aarti. If you are gifting someone who observes the fast, this matters. Consider:' },
      { type: 'ul', items: [
        'Coconut ladoo — fasting-friendly, delicious, and long-lasting at room temperature',
        'Til (sesame) based mukhwas — seeds are fasting-permissible for most observers',
        'Dry fruit mixes — dates, cashews, and almonds are Navratri staples',
        'Rock salt-seasoned snacks — sendha namak is permitted during fasting while regular salt is not',
        'Sabudana (tapioca) based snacks — widely consumed during Navratri fasting',
      ]},
      { type: 'h2', text: 'Non-Fasting Navratri Hamper Ideas' },
      { type: 'p', text: 'If your recipient does not fast, Navratri is a wonderful excuse to send a broader homemade hamper. Think a curated mix of:' },
      { type: 'ul', items: [
        'Freshly made chakli and namkeen for evening snacking',
        'A selection of mukhwas for after the garba night',
        'Til ladoo or besan ladoo as the sweet centerpiece',
        'A jar of homemade masala or chutney powder for the festive kitchen',
        'Premium dry fruits to round out the hamper',
      ]},
      { type: 'h2', text: 'Corporate Gifting During Navratri' },
      { type: 'p', text: 'In Gujarat, businesses often gift during Navratri as well as Diwali. This is particularly meaningful in Ahmedabad where Navratri is a community-wide festival. A handcrafted homemade hamper from a local home kitchen — with a card that acknowledges the festival season — feels far more personal and culturally attuned than a corporate branded gift box. It shows that you know your audience and respect their traditions.' },
      { type: 'h2', text: 'Packaging for Navratri' },
      { type: 'p', text: 'Navratri colors are vibrant — red, orange, yellow, green, and gold. A hamper packaged in these tones, with a red or gold ribbon, and a hand-written note referencing the nine nights of celebration will immediately feel festive and intentional. The packaging is the first impression; make it match the energy of the occasion.' },
      { type: 'tip', heading: 'Order Ahead for Navratri', text: 'Navratri dates shift each year based on the lunar calendar. At Amie\'s, we begin accepting Navratri hamper orders 10 days before the festival begins. Message us on WhatsApp to reserve your batch — quantities are limited as everything is made fresh and in small batches.' },
      { type: 'p', text: 'Navratri is about devotion, community, and the joy of being together. When you gift someone something made with genuine care and real ingredients, you are adding your own small offering to the spirit of the season. That is the kind of gift that actually matters.' },
    ],
  },

  // ── POST 12 ───────────────────────────────────────────────────────────────
  {
    id: 'post-12',
    slug: 'corporate-gifting-india-complete-guide-2026',
    title: 'Corporate Gifting in India 2026: A Complete Guide to Getting It Right',
    excerpt: 'Most corporate gifting is forgettable. The companies that get it right understand one thing: a gift is not a transaction, it is a conversation. Here\'s how to make yours memorable.',
    coverImage: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-04-15',
    readTime: 6,
    category: 'Corporate Gifting',
    categoryColor: 'bg-blue-100 text-blue-700',
    tags: ['corporate', 'gifting', 'business', 'bulk', 'diwali'],
    content: [
      { type: 'p', text: 'Every year, Indian companies spend thousands of crores on corporate gifts. And most of that money is spent on things that will be forgotten within 48 hours of being received. Branded pens sit in drawers. Desk organizers gather dust. Diaries go unopened. The companies that get corporate gifting right understand something fundamental: a gift is not a transaction, it is a conversation. And the quality of that conversation determines how you are remembered.' },
      { type: 'h2', text: 'Why Most Corporate Gifts Fail' },
      { type: 'ul', items: [
        'They are generic — the same thing that every other company sends',
        'They are impersonal — nothing about the gift acknowledges who the recipient actually is',
        'They are forgettable — the gift creates no lasting memory or association',
        'They are wasteful — items are discarded, adding to environmental cost with zero relationship benefit',
        'They feel transactional — the message conveyed is "we had to send something", not "we thought of you"',
      ]},
      { type: 'h2', text: 'What the Best Corporate Gifts Have in Common' },
      { type: 'p', text: 'The corporate gifts that get talked about in offices — that people actually mention to colleagues, that create genuine goodwill — share several qualities. They are consumable (food is the clearest example — it gets enjoyed, not discarded). They are culturally resonant (they reflect an understanding of the recipient\'s context). They feel handcrafted (even if they are from a small producer, the personal quality is apparent). And they are presented beautifully.' },
      { type: 'h2', text: 'Why Homemade Food Hampers Win for Corporate Gifting' },
      { type: 'p', text: 'In India\'s corporate culture, food has always been a natural vehicle for relationship-building. Shared meals, chai meetings, festival sweets at the office — food creates warmth that objects cannot. A well-curated homemade food hamper does several things simultaneously: it showcases the giver\'s taste and discernment, it provides an experience (the act of eating together), and it carries cultural significance that resonates across India\'s diverse professional landscape.' },
      { type: 'h2', text: 'Planning a Corporate Hamper Order' },
      { type: 'h3', text: 'Step 1: Define Your Budget per Recipient' },
      { type: 'p', text: 'Corporate gifting typically falls into three tiers: ₹300–700 per person (staff and wider network), ₹700–1,500 per person (clients and partners), and ₹1,500+ per person (senior clients, VIP relationships, key vendors). Your hamper contents should be calibrated to each tier while maintaining a consistent quality baseline. A premium product in a simpler box is always better than a mediocre product in elaborate packaging.' },
      { type: 'h3', text: 'Step 2: Think About the Occasion' },
      { type: 'p', text: 'Diwali remains India\'s most significant corporate gifting moment. But smart companies also gift at: Navratri (especially in Gujarat), New Year, Holi (the second biggest occasion in many industries), Eid (for businesses with significant Muslim clientele or staff), and at client milestone moments (first anniversary, project completion, annual reviews).' },
      { type: 'h3', text: 'Step 3: Personalize Where Possible' },
      { type: 'p', text: 'At scale, full personalization is not practical. But even small gestures matter: a handwritten card with the recipient\'s name, a reference to something specific in your relationship, or the ability to choose between 2–3 curated hamper options. At Amie\'s, bulk orders include customization of card messaging, and for orders above 50 units, we offer custom packaging with your company name.' },
      { type: 'h3', text: 'Step 4: Order Early, Very Early' },
      { type: 'p', text: 'This is the single biggest mistake in corporate gifting. Companies leave orders until two weeks before Diwali, then struggle with availability, quality, and delivery logistics. For bulk orders of homemade products — where everything is made fresh in small batches — an ideal lead time is 4–6 weeks. This ensures product freshness, delivery reliability, and the ability to customize.' },
      { type: 'quote', text: 'The best corporate gift is one that your client mentions to their colleague at lunch. Not because it was expensive — but because it was thoughtful.' },
      { type: 'h2', text: 'What to Include in a Premium Corporate Hamper' },
      { type: 'ul', items: [
        'A selection of 3–5 mukhwas varieties in sealed glass jars — visually striking and culturally meaningful',
        'One or two homemade snack items (chakli, namkeen) for savory balance',
        'One sweet item (besan ladoo, til ladoo) for the festive gesture',
        'A handwritten note or custom printed card with your message',
        'A presentation box that the recipient will want to keep',
      ]},
      { type: 'tip', heading: 'The ROI of a Memorable Gift', text: 'A corporate gift that is talked about and remembered is worth 10x what a forgettable gift costs. Spending ₹1,200 per client on a handcrafted food hamper that genuinely impresses is a far better investment than spending ₹800 on a branded diary that ends up in the recycling bin. Think of it as marketing budget, not overhead.' },
      { type: 'p', text: 'Corporate gifting is not just a protocol — it is an opportunity. Every hamper you send is a chance to remind someone why they chose to work with you. Make it count.' },
    ],
  },

  // ── POST 8 ───────────────────────────────────────────────────────────────
  {
    id: 'post-8',
    slug: 'best-mukhwas-in-ahmedabad-local-guide',
    title: 'The Best Mukhwas in Ahmedabad: A Local\'s Honest Guide',
    excerpt: 'Ahmedabad takes its mukhwas seriously. From the old city\'s traditional shops to the rise of home kitchens making it fresh — here\'s everything you need to know about finding the real thing.',
    coverImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-03-30',
    readTime: 4,
    category: 'Ahmedabad',
    categoryColor: 'bg-teal-100 text-teal-700',
    tags: ['ahmedabad', 'mukhwas', 'local', 'guide'],
    content: [
      { type: 'p', text: 'Ahmedabad has always been a city of food obsessives. From the legendary Manek Chowk to the iconic snack shops of Navrangpura, this city takes its culinary heritage seriously. And mukhwas — that colorful, fragrant ritual of seeds and spices that ends every Gujarati meal — is no exception. Here is everything you need to know about finding genuinely good mukhwas in Ahmedabad.' },
      { type: 'h2', text: 'What Makes Ahmedabad\'s Mukhwas Culture Unique' },
      { type: 'p', text: 'Ahmedabad\'s mukhwas culture is distinct for a few reasons. First, the sheer variety — you will find everything from plain saunf to elaborate 15-ingredient mixes with dried coconut, colored sugar pearls, and silver-coated cardamom. Second, the presentation: Ahmedabad mukhwas shops are a visual experience, with gleaming silver trays and ornate displays. Third, and most importantly, the ritual: mukhwas is not an afterthought here. It is the expected, graceful conclusion to any meal.' },
      { type: 'h2', text: 'The Old City vs. The New City Mukhwas Scene' },
      { type: 'p', text: 'The old city — Manek Chowk, Kalupur, Raipur Darwaja — is home to the most traditional mukhwas sellers. These are shops that have been around for decades, with glass jars of saunf, fennel, dhana, and pan masala sitting on worn wooden counters. The new city — Vastrapur, Satellite, Prahlad Nagar, Thaltej — has seen the rise of modern gifting stores and home-based businesses that bring the same traditional recipes with better packaging and hygiene standards.' },
      { type: 'h2', text: 'What to Look For When Buying Mukhwas in Ahmedabad' },
      { type: 'ul', items: [
        'Freshness: Does the seller know when it was made? Good mukhwas should be fresh, not sitting for months in a warehouse.',
        'Color: Natural, muted tones — light green for saunf, beige for coriander. Not neon artificial hues.',
        'Storage: Is it kept in airtight containers away from direct sunlight and moisture? This matters enormously for shelf life and quality.',
        'Ingredients: If it is pre-packaged, read the label. Avoid long lists with chemical names you cannot pronounce.',
        'Taste: Good mukhwas tastes clean, fresh, and genuinely fragrant. If it tastes artificial or excessively sweet, it has been commercially over-processed.',
      ]},
      { type: 'h2', text: 'Why Home Kitchens Are the Future of Mukhwas' },
      { type: 'p', text: 'The best mukhwas in Ahmedabad today is no longer coming from big commercial brands. It is coming from home kitchens — where recipes have not been compromised for shelf life, where ingredients are sourced fresh, and where the person making it has a genuine relationship with what they are producing. This is a quiet but meaningful shift in how the city\'s food culture is evolving.' },
      { type: 'h2', text: 'Amie\'s Homemade: Ahmedabad\'s Home-Kitchen Standard' },
      { type: 'p', text: 'Ami Shah began making mukhwas the way her mother taught her — with real ingredients, no shortcuts, and an obsessive eye toward getting the flavor exactly right. Today, Amie\'s ships fresh mukhwas across Ahmedabad and pan-India. Every batch is still made by hand, in small quantities, with nothing artificial added. The ingredient list fits on a single line.' },
      { type: 'tip', heading: 'Ordering in Ahmedabad', text: 'Amie\'s offers free home delivery across Ahmedabad, typically within 1 business day of your order. Message directly on WhatsApp to place your order and know exactly when your batch was made.' },
      { type: 'p', text: 'Ahmedabad\'s mukhwas culture is one of the city\'s great quiet pleasures. Whether you are a lifelong resident or visiting for the first time, finding genuinely fresh, fragrant mukhwas — made with honest ingredients by someone who cares — is one of the best culinary experiences this city has to offer.' },
    ],
  },
  // ── POST 13 ───────────────────────────────────────────────────────────────
  {
    id: 'post-13',
    slug: 'gujarati-namkeen-farsan-guide',
    title: 'Gujarati Namkeen and Farsan: The Snacks That Define a Culture',
    excerpt: 'Gujarat\'s farsan tradition is one of the most diverse and delicious snack cultures in the world. These are not just snacks — they are an identity. Here\'s everything you need to know.',
    coverImage: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-04-19',
    readTime: 5,
    category: 'Homemade Snacks',
    categoryColor: 'bg-orange-100 text-orange-700',
    tags: ['namkeen', 'farsan', 'gujarati', 'snacks', 'homemade'],
    content: [
      { type: 'p', text: 'If you want to understand Gujarati food culture, start with farsan. Not with dhokla (though that is iconic), not with khandvi (though that is a miracle of technique), but with farsan in its broadest sense — the entire universe of Gujarati savory snacks that accompanies every cup of chai, fills every gift hamper, and defines the hospitality of every home. Gujarat\'s snack culture is not an accident. It emerged from centuries of trade, community, and an insistence on flavor that runs through everything the state produces.' },
      { type: 'h2', text: 'What is Farsan?' },
      { type: 'p', text: 'Farsan (also spelled farsaan) is the Gujarati term for savory snacks — a broad category that encompasses everything from the delicate steamed dhokla to the robust crunch of chakli. The word comes from the Sanskrit "bharshan," meaning that which fills. In everyday Gujarati households, farsan is served as a side dish at meals, as a tea-time snack, at celebrations, and as the backbone of any good gift hamper. It is not a single dish but a tradition.' },
      { type: 'h2', text: 'The Essential Gujarati Farsan Varieties' },
      { type: 'h3', text: 'Chakli (Murukku)' },
      { type: 'p', text: 'The queen of Gujarati farsan — a spiral-shaped fried snack made from rice flour and lentil flour, flavored with sesame and ajwain. Gujarati chakli tends to be slightly softer and less intensely spiced than its South Indian counterpart murukku. It is a Diwali staple and one of the most gifted homemade snacks in the state.' },
      { type: 'h3', text: 'Sev' },
      { type: 'p', text: 'Thin or thick fried noodles of besan (chickpea flour), sev is perhaps the most versatile farsan item. It can be eaten plain, mixed into bhel, or used as a topping for dozens of street foods. Homemade sev — especially the thick, masala variety — has a depth of flavor that packaged sev simply cannot replicate. The oil used for frying and the ratio of spices make all the difference.' },
      { type: 'h3', text: 'Gathiya' },
      { type: 'p', text: 'Thick, soft strands of fried besan seasoned with black pepper, gathiya is one of the most distinctly Gujarati snacks. Surati gathiya (from the Surat region) is particularly beloved — faintly sweet, with a crumbly texture unlike any other farsan. It is commonly eaten for breakfast in Gujarat with chai and green chutney. Good gathiya should melt slightly in the mouth, not crunch aggressively.' },
      { type: 'h3', text: 'Khakhra' },
      { type: 'p', text: 'A thin, crisp flatbread made from wheat flour and roasted on a tawa until completely dehydrated and crispy, khakhra is Gujarat\'s great everyday snack. The best khakhra is thin, evenly golden, and shatters cleanly when broken. It comes in dozens of flavors — plain, methi (fenugreek), masala, jeera — and lasts for weeks in an airtight container. It is one of the most practical snacks to gift because of its shelf life and versatility.' },
      { type: 'h3', text: 'Namkeen Mixes' },
      { type: 'p', text: 'The catch-all term for mixed salty snacks — combinations of sev, peanuts, flattened rice, sesame sticks, and dried peas mixed with spices. Every home cook has their own namkeen mix formula, and no two are exactly alike. Good namkeen has a balance of textures (crunchy, chewy, light) and flavors (salty, spiced, slightly tangy) that makes it impossible to eat just one handful.' },
      { type: 'h2', text: 'Why Homemade Farsan Is a Different Experience' },
      { type: 'p', text: 'The commercial farsan industry in India is enormous — brands like Haldiram\'s, Bikaji, and Balaji have built empires on these snacks. And they do a reasonable job. But homemade farsan operates on different principles. The oil is fresh for each batch. The spice ratios are precise to the maker\'s taste. The quantities are small, meaning the frying temperature stays consistent. The result is a product that tastes noticeably more alive — more fragrant, more textured, more real.' },
      { type: 'h2', text: 'Farsan in Gift Hampers' },
      { type: 'p', text: 'A well-composed farsan hamper is one of the most universally appreciated Indian gifts. Unlike sweets (which some people avoid for health reasons) or mukhwas (which is quite niche to people unfamiliar with the tradition), farsan appeals to virtually everyone. Mix 3–4 varieties at different heat levels, add a jar of green chutney or garlic pickle, and you have a gift that will be enjoyed over several weeks.' },
      { type: 'tip', heading: 'The Best Farsan Combinations for Gifting', text: 'A classic Gujarati farsan hamper should include something crispy (chakli), something light (sev), something filling (namkeen mix), and something versatile (khakhra). This four-way variety ensures there is something for every mood and occasion throughout the recipient\'s day.' },
      { type: 'p', text: 'Gujarat\'s snack culture is the product of centuries of refinement by people who took the art of eating seriously. When you buy or gift homemade Gujarati farsan, you are not just buying a snack — you are carrying a piece of that tradition forward.' },
    ],
  },

  // ── POST 14 ───────────────────────────────────────────────────────────────
  {
    id: 'post-14',
    slug: 'raksha-bandhan-gifts-beyond-mithai-box',
    title: 'Raksha Bandhan Gift Ideas: Beyond the Standard Mithai Box',
    excerpt: 'Raksha Bandhan is one of India\'s most personal festivals — the bond between siblings deserves something more thoughtful than the same box of kaju katli every year. Here\'s how to make it memorable.',
    coverImage: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-04-23',
    readTime: 4,
    category: 'Festive Gifting',
    categoryColor: 'bg-pink-100 text-pink-700',
    tags: ['raksha bandhan', 'gifting', 'siblings', 'festival', 'homemade'],
    content: [
      { type: 'p', text: 'Raksha Bandhan is the most personal festival in the Indian calendar. The bond between siblings — the teasing, the protectiveness, the shared childhood — is celebrated with a ritual that has remained essentially unchanged for thousands of years. Which makes it all the more surprising that the gifting associated with it has become so predictable. If you have received the same box of kaju katli from your sibling three years in a row, you know exactly what we mean. This year, let\'s do better.' },
      { type: 'h2', text: 'Why Raksha Bandhan Gifting Deserves More Thought' },
      { type: 'p', text: 'This is not a corporate occasion where gifts are meant to impress strangers. This is your sibling. The person who knows your favorite flavor, your food preferences, your childhood snack memories. Raksha Bandhan gifting should reflect that intimacy — something that says "I actually know you" rather than "I got you the standard thing." That is why personalized, homemade food gifts work so well for this festival.' },
      { type: 'h2', text: 'Homemade Gift Ideas by Sibling Type' },
      { type: 'h3', text: 'For the Health-Conscious Sibling' },
      { type: 'p', text: 'Skip the sugar-loaded mithai and send something that aligns with how they actually eat. A curated hamper of sugar-free mukhwas, roasted seed mixes, plain fennel and coriander blends, and natural dry fruits sends a message: "I see how you live, and I respect it." This is particularly appreciated by siblings who have recently changed their eating habits for health reasons or are managing conditions like diabetes.' },
      { type: 'h3', text: 'For the Traditionalist Sibling' },
      { type: 'p', text: 'Some siblings love nothing more than real, traditional mithai and snacks made the old way. For them, a hamper of homemade chakli, besan ladoo, mixed mukhwas, and perhaps a small jar of homemade masala chutney will feel like a return to childhood. The key is that it is genuinely homemade — not store-bought dressed up in nice packaging. They will taste the difference immediately.' },
      { type: 'h3', text: 'For the Sibling Far Away' },
      { type: 'p', text: 'If your sibling lives in a different city — or if you are the one who has moved away — Raksha Bandhan becomes especially meaningful. Sending a homemade hamper from Ahmedabad to your sibling in Mumbai, Bangalore, or Delhi carries the message: "I sent you a piece of home." Amie\'s ships pan-India, and the products are made fresh and packed for travel. The hamper arrives with the aromas of home, which is the point.' },
      { type: 'h3', text: 'For the Brother or Sister with Kids' },
      { type: 'p', text: 'If your sibling has young children, the gift becomes a family gift by default. A snack hamper with chakli, sev, namkeen, and a sweet like coconut ladoo becomes a household gift that everyone will enjoy. Children especially love the variety — the ability to pick what they want from a beautiful hamper is its own kind of joy.' },
      { type: 'h2', text: 'The Homemade Advantage for Raksha Bandhan' },
      { type: 'p', text: 'Commercial mithai boxes have their place — but for a festival this personal, the handmade quality of a homemade hamper communicates something that a branded box cannot. Every piece of chakli that Ami Shah makes is made by hand. Every ladoo is hand-rolled. Every jar of mukhwas has been mixed and packed with attention. That handmade quality is visible and tangible when you hold it — and it transforms the gifting experience from transactional to genuinely meaningful.' },
      { type: 'tip', heading: 'Add a Note That Actually Says Something', text: 'Include a handwritten note — not just "Happy Raksha Bandhan," but something personal. A memory you share, a private joke, or simply: "I made sure this was homemade because you deserve real things." The note costs nothing but makes the gift unforgettable.' },
      { type: 'p', text: 'Raksha Bandhan is one of the few occasions where the gift is secondary to the feeling behind it. But when the feeling is backed by something genuinely thoughtful — something made with care, chosen with your sibling specifically in mind — the combination is hard to beat.' },
    ],
  },

  // ── POST 15 ───────────────────────────────────────────────────────────────
  {
    id: 'post-15',
    slug: 'homemade-barfi-guide-varieties',
    title: 'Homemade Barfi: India\'s Most Elegant Mithai and Why Homemade Still Wins',
    excerpt: 'Barfi is the mithai of celebrations — smooth, dense, and infinitely variable. But the gap between commercially made barfi and the real homemade thing is wider than you might think.',
    coverImage: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-04-27',
    readTime: 5,
    category: 'Homemade Sweets',
    categoryColor: 'bg-yellow-100 text-yellow-800',
    tags: ['barfi', 'mithai', 'sweets', 'homemade', 'gifting'],
    content: [
      { type: 'p', text: 'If you want to judge a mithai shop — or a home cook — by a single dish, order the barfi. This deceptively simple sweet reveals everything: the quality of the base ingredient, the precision of the cooking, the freshness of the milk or nut paste, and the restraint of the sweetener. Barfi cannot be faked. Commercial short-cuts show immediately in the texture and flavor. This is why truly good barfi, made from scratch with genuine ingredients, remains one of the most impressive homemade gifts you can offer.' },
      { type: 'h2', text: 'What Is Barfi?' },
      { type: 'p', text: 'Barfi (also spelled burfi) is a dense, fudge-like Indian confection made by cooking a base ingredient — milk solids, nut flour, or pulses — with sugar and ghee until it reaches a firm, sliceable consistency. The name is believed to derive from the Persian "barf" meaning snow, likely referencing the white appearance of milk-based varieties. Unlike ladoo, which is shaped into spheres, barfi is typically set in a tray and cut into diamonds or squares, often garnished with silver leaf (varq) or a single pistachio.' },
      { type: 'h2', text: 'The Classic Barfi Varieties' },
      { type: 'h3', text: 'Kaju Barfi (Cashew Barfi)' },
      { type: 'p', text: 'The most celebrated of all barfis — smooth cashew paste cooked with sugar syrup to a fudge-like consistency, then rolled thin and cut into diamond shapes. Good kaju barfi is expensive to make (quality cashews are priced accordingly) and the technique is exacting. The sugar syrup must reach exactly the right thread consistency, or the barfi will either be too sticky or too hard. When it is right, kaju barfi has a clean, buttery richness that is deeply satisfying in small quantities.' },
      { type: 'h3', text: 'Besan (Chickpea Flour) Barfi' },
      { type: 'p', text: 'More commonly found in Rajasthan and Gujarat than in North India, besan barfi is made by roasting besan in ghee until golden, then combining it with sugar syrup and setting it in trays. It has a distinctly nutty flavor that differentiates it from milk-based barfis. A well-made besan barfi has a slightly grainy texture — the natural result of the flour — which is part of its appeal.' },
      { type: 'h3', text: 'Nariyal (Coconut) Barfi' },
      { type: 'p', text: 'Made from freshly grated or desiccated coconut cooked with condensed milk or sugar, nariyal barfi is moist, fragrant, and one of the more perishable varieties. The quality of the coconut determines everything — fresh coconut produces a naturally fragrant barfi with a clean sweetness. Desiccated coconut can work beautifully if it is high-quality. Low-quality desiccated coconut produces a dry, flavorless result that no amount of sugar can rescue.' },
      { type: 'h3', text: 'Anjeer (Fig) Barfi' },
      { type: 'p', text: 'A more artisanal variety, anjeer barfi uses dried figs as the base — blended with nuts, cardamom, and a small amount of ghee, then set into a dense, intensely flavored block. It is naturally sweetened by the figs and tends to be richer in nutrients than sugar-based barfis. Anjeer barfi has become increasingly popular as a "healthier mithai" option and is particularly well-received as a gift.' },
      { type: 'h2', text: 'Why Homemade Barfi Is Superior' },
      { type: 'ul', items: [
        'No Hydrogenated Fats: Commercial barfi often uses vanaspati (hydrogenated vegetable fat) instead of ghee. The difference in flavor is dramatic — ghee produces a clean, rich finish; vanaspati produces a waxy, slightly unpleasant aftertaste.',
        'No Artificial Flavors: Real kaju barfi tastes like cashews. Real nariyal barfi tastes like coconut. Commercial versions often contain artificial cardamom or vanilla flavor to compensate for low-quality bases.',
        'No Excessive Preservation: Commercial barfi is made to last weeks on shelves. Homemade barfi is meant to be consumed within days — this means the texture and flavor are calibrated for freshness, not shelf life.',
        'Genuine Silver Leaf: Traditional barfi is garnished with real edible silver leaf (varq). Many commercial products use imitation silver foil. The real thing adds an authentic visual and cultural touch.',
      ]},
      { type: 'h2', text: 'Barfi as a Festival Gift' },
      { type: 'p', text: 'Barfi is the mithai of celebration. It is offered at temples, distributed at weddings, gifted at Diwali and Raksha Bandhan, shared at births and anniversaries. Its diamond shape and silver garnish have made it the visual icon of Indian festive sweetness. A box of genuinely homemade barfi — especially kaju barfi — is one of the highest-impact food gifts you can give. The presentation is inherently beautiful; the quality speaks for itself.' },
      { type: 'tip', heading: 'How to Store Barfi', text: 'Milk-based and nut-based barfi should be stored in an airtight container in the refrigerator and consumed within 5–7 days. Nariyal barfi is more perishable and should be consumed within 3–4 days. Allow refrigerated barfi to come to room temperature for 10–15 minutes before serving — cold barfi loses much of its flavor and texture nuance.' },
      { type: 'p', text: 'Good barfi is a reminder that Indian mithai, at its best, is one of the great confectionery traditions of the world. Not because it is simple — genuine barfi requires real skill and real ingredients. But because when it is made correctly, it delivers a flavor experience that is deeply satisfying in a way that nothing else quite matches.' },
    ],
  },

  // ── POST 16 ───────────────────────────────────────────────────────────────
  {
    id: 'post-16',
    slug: 'festive-hampers-best-indian-corporate-gift',
    title: 'Why Festive Hampers Are the Best Indian Corporate Gift — For Every Occasion',
    excerpt: 'India has 29 major public holidays, dozens of regional festivals, and a business culture where relationship-building is everything. Here\'s why a thoughtful festive hamper beats every other corporate gift option.',
    coverImage: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=1600&auto=format&fit=crop',
    publishedAt: '2026-05-01',
    readTime: 5,
    category: 'Corporate Gifting',
    categoryColor: 'bg-blue-100 text-blue-700',
    tags: ['corporate', 'hamper', 'gifting', 'festivals', 'business'],
    content: [
      { type: 'p', text: 'India is, by any measure, the world\'s most festival-rich country for business gifting. Between Diwali, Navratri, Eid, Holi, Pongal, Onam, Ganesh Chaturthi, Baisakhi, and dozens of regional celebrations, there is barely a month in the Indian calendar that does not offer a meaningful occasion to gift to clients, partners, and colleagues. Most companies use this opportunity poorly. The ones that use it well build relationships that last decades.' },
      { type: 'h2', text: 'The Festival Calendar as a Business Strategy' },
      { type: 'p', text: 'Forward-thinking businesses do not just gift at Diwali. They treat the Indian festival calendar as a 12-month relationship-building opportunity. A Navratri hamper sent in October (especially in Gujarat) makes an impression precisely because few businesses think to do it. A Holi gift in March stands out because most corporate gifting has slowed after the Diwali rush. The element of unexpectedness multiplies the impact of the gift significantly.' },
      { type: 'h2', text: 'What Makes a Hamper Better Than Any Other Corporate Gift' },
      { type: 'ul', items: [
        'It gets shared — food gifts are opened and enjoyed with family, extending the brand impression beyond the initial recipient',
        'It gets talked about — a distinctive, high-quality hamper becomes a conversation at the dinner table ("Look what our client sent")',
        'It is consumable — unlike objects that sit in drawers, food gets fully experienced and creates a sensory memory associated with your brand',
        'It is culturally intelligent — in India, sharing food is the most natural form of hospitality and relationship-building',
        'It is timely — festive gifting has built-in context and emotional resonance that non-festive gifts lack',
      ]},
      { type: 'h2', text: 'Matching Hampers to Festivals' },
      { type: 'h3', text: 'Diwali (October/November)' },
      { type: 'p', text: 'The premium occasion for corporate hampers. Emphasis on abundance, celebration, and quality. A Heritage Box with mukhwas, snacks, and a sweet item in a wooden presentation case is ideal. Order at least 6 weeks in advance. Budget: ₹800–₹2,500+ per recipient depending on tier.' },
      { type: 'h3', text: 'Navratri (October — especially in Gujarat)' },
      { type: 'p', text: 'Particularly meaningful for businesses operating in Gujarat or with Gujarati clients. A hamper featuring fasting-friendly items (coconut ladoo, roasted seeds, dry fruits) or a classic farsan hamper (chakli, namkeen, mukhwas) is culturally attuned. The fact that few businesses gift during Navratri makes this an opportunity to stand out.' },
      { type: 'h3', text: 'Holi (March)' },
      { type: 'p', text: 'India\'s most joyful festival is underutilized in corporate gifting. A colorful hamper — perhaps with varieties of mukhwas in different colors, thandai mix, or a snack assortment — captures the spirit of the festival. It arrives in Q1, keeping your business top of mind as clients plan the year ahead.' },
      { type: 'h3', text: 'New Year / Makar Sankranti (January)' },
      { type: 'p', text: 'The calendar new year and the harvest festival Makar Sankranti (celebrated in January across India in different forms) offer a natural Q1 gifting window. Til ladoo — the traditional Sankranti sweet — is a distinctive and culturally resonant choice. For New Year gifting, a "fresh start" wellness hamper theme (natural seeds, mukhwas, sugar-free options) works well.' },
      { type: 'h2', text: 'How to Place a Bulk Hamper Order' },
      { type: 'p', text: 'At Amie\'s Homemade, corporate bulk orders are available with a minimum of 10 hampers. The process is simple: share your recipient count and budget per person over WhatsApp, receive a curated recommendation, approve the contents and packaging, and your order will be freshly made and delivered within the agreed timeline. For orders above 25 units, custom branding and card messaging is available.' },
      { type: 'h2', text: 'The Long-Term Value of Thoughtful Gifting' },
      { type: 'p', text: 'A single exceptional gift is remembered. A consistent pattern of thoughtful gifting — year after year, festival after festival — builds a reputation. Clients begin to look forward to what you will send. Partners mention your company\'s warmth when recommending you to others. This is the compounding return on investment that generic corporate gifting can never produce.' },
      { type: 'quote', text: 'In a business culture where personal relationships are everything, how you gift tells people as much about your company as your pitch deck does.' },
      { type: 'tip', heading: 'Plan Your Gifting Calendar Now', text: 'At the start of the year, map out which festivals are relevant to your client base and decide which occasions you will gift. Build this into your marketing budget, not your miscellaneous expenses. Message Amie\'s on WhatsApp to discuss your annual gifting plan — we can advise on what to send, when, and how to customize it for maximum impact.' },
      { type: 'p', text: 'The Indian business calendar is a gift — quite literally. Twenty-nine public holidays and dozens of regional festivals are twenty-nine reasons to reach out to someone who matters to your business and say: we thought of you. Use it well.' },
    ],
  },

];

// Returns only posts whose publishedAt date has passed (auto-scheduling)
export const getPublishedPosts = (): BlogPost[] => {
  const today = new Date().toISOString().split('T')[0];
  return BLOG_POSTS.filter(p => p.publishedAt <= today);
};

export const getPostBySlug = (slug: string): BlogPost | undefined =>
  BLOG_POSTS.find(p => p.slug === slug);

export const getRelatedPosts = (post: BlogPost, limit = 3): BlogPost[] => {
  const today = new Date().toISOString().split('T')[0];
  return BLOG_POSTS
    .filter(p => p.id !== post.id && p.publishedAt <= today && p.category === post.category)
    .slice(0, limit);
};
